/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko_sembako;

import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fadhilansyah25
 */
public class Dashboard extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    String id_barang, id_supplier;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        koneksi();
        // Method Panel Barang
        loadTabel_barang();
        kosongkan_formBarang();
        comboBox_formbarang();

        // Method Panel Supplier
        loadTabel_supplier();
        kosongkan_formSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        dataBarang_tabBut = new javax.swing.JPanel();
        dataBarang_tg = new javax.swing.JLabel();
        dataSupplier_tabBut = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dataPenjualan_tabBut = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout_label = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTkode_barang = new javax.swing.JTextField();
        JTnama_barang = new javax.swing.JTextField();
        JTsatuan_barang = new javax.swing.JTextField();
        JTsupplier_barang = new javax.swing.JTextField();
        JTstok_barang = new javax.swing.JTextField();
        JTharga_barang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BTinsert_barang = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        BTedit_barang = new javax.swing.JButton();
        BTdelete_barang = new javax.swing.JButton();
        CBnamaSupplier = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        BTrefresh_barang = new javax.swing.JButton();
        panelSupplier = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_supplier = new javax.swing.JTable();
        JTidSupplier_supplier = new javax.swing.JTextField();
        JTnama_supplier = new javax.swing.JTextField();
        JTnomor_supplier = new javax.swing.JTextField();
        JTalamat_supplier = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BTadd_supplier = new javax.swing.JButton();
        BTedit_supplier = new javax.swing.JButton();
        BTdelete_supplier = new javax.swing.JButton();
        BTrefresh_supplier = new javax.swing.JButton();
        panelPenjualan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        sidePanel.setBackground(new java.awt.Color(255, 51, 51));
        sidePanel.setPreferredSize(new java.awt.Dimension(250, 600));

        dataBarang_tabBut.setBackground(new java.awt.Color(255, 153, 0));
        dataBarang_tabBut.setPreferredSize(new java.awt.Dimension(200, 50));
        dataBarang_tabBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataBarang_tabButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataBarang_tabButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataBarang_tabButMouseExited(evt);
            }
        });

        dataBarang_tg.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        dataBarang_tg.setForeground(new java.awt.Color(255, 255, 255));
        dataBarang_tg.setText("DATA BARANG");

        javax.swing.GroupLayout dataBarang_tabButLayout = new javax.swing.GroupLayout(dataBarang_tabBut);
        dataBarang_tabBut.setLayout(dataBarang_tabButLayout);
        dataBarang_tabButLayout.setHorizontalGroup(
            dataBarang_tabButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarang_tabButLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(dataBarang_tg)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        dataBarang_tabButLayout.setVerticalGroup(
            dataBarang_tabButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarang_tabButLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataBarang_tg, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        dataSupplier_tabBut.setBackground(new java.awt.Color(255, 153, 0));
        dataSupplier_tabBut.setPreferredSize(new java.awt.Dimension(200, 50));
        dataSupplier_tabBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataSupplier_tabButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataSupplier_tabButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataSupplier_tabButMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA SUPPLIER");

        javax.swing.GroupLayout dataSupplier_tabButLayout = new javax.swing.GroupLayout(dataSupplier_tabBut);
        dataSupplier_tabBut.setLayout(dataSupplier_tabButLayout);
        dataSupplier_tabButLayout.setHorizontalGroup(
            dataSupplier_tabButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataSupplier_tabButLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataSupplier_tabButLayout.setVerticalGroup(
            dataSupplier_tabButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataSupplier_tabButLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dataPenjualan_tabBut.setBackground(new java.awt.Color(255, 153, 0));
        dataPenjualan_tabBut.setPreferredSize(new java.awt.Dimension(200, 50));
        dataPenjualan_tabBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPenjualan_tabButMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataPenjualan_tabButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataPenjualan_tabButMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PENJUALAN");

        javax.swing.GroupLayout dataPenjualan_tabButLayout = new javax.swing.GroupLayout(dataPenjualan_tabBut);
        dataPenjualan_tabBut.setLayout(dataPenjualan_tabButLayout);
        dataPenjualan_tabButLayout.setHorizontalGroup(
            dataPenjualan_tabButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenjualan_tabButLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataPenjualan_tabButLayout.setVerticalGroup(
            dataPenjualan_tabButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPenjualan_tabButLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logout_label.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        logout_label.setForeground(new java.awt.Color(255, 255, 255));
        logout_label.setText("Log out");
        logout_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_labelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(dataBarang_tabBut, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(dataSupplier_tabBut, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(dataPenjualan_tabBut, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logout_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(dataBarang_tabBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dataSupplier_tabBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dataPenjualan_tabBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_label)
                .addGap(26, 26, 26))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        panelBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("DATA BARANG");

        JTsupplier_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTsupplier_barangMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel5.setText("Kode Barang");

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setText("Nama Barang");

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel7.setText("Satuan");

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel8.setText("ID Supplier");

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel9.setText("Stok");

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel10.setText("Harga Satuan");

        BTinsert_barang.setText("Add Data");
        BTinsert_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTinsert_barangActionPerformed(evt);
            }
        });

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_barang);

        BTedit_barang.setText("Edit Data");
        BTedit_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTedit_barangActionPerformed(evt);
            }
        });

        BTdelete_barang.setText("Delete Data");
        BTdelete_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTdelete_barangActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel11.setText("Nama Supplier");

        BTrefresh_barang.setText("Refresh All");
        BTrefresh_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTrefresh_barangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBarangLayout = new javax.swing.GroupLayout(panelBarang);
        panelBarang.setLayout(panelBarangLayout);
        panelBarangLayout.setHorizontalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTharga_barang)
                                .addComponent(JTstok_barang)
                                .addComponent(JTsupplier_barang)
                                .addComponent(JTsatuan_barang)
                                .addComponent(JTnama_barang)
                                .addComponent(JTkode_barang, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(CBnamaSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelBarangLayout.createSequentialGroup()
                                    .addComponent(BTinsert_barang)
                                    .addGap(18, 18, 18)
                                    .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BTrefresh_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTedit_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(BTdelete_barang)))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        panelBarangLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BTdelete_barang, BTedit_barang, BTinsert_barang});

        panelBarangLayout.setVerticalGroup(
            panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(panelBarangLayout.createSequentialGroup()
                        .addComponent(JTkode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTnama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTsatuan_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBnamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTsupplier_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTstok_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTharga_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(panelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTinsert_barang)
                    .addComponent(BTedit_barang)
                    .addComponent(BTdelete_barang))
                .addGap(31, 31, 31)
                .addComponent(BTrefresh_barang)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        mainPanel.add(panelBarang, "card2");

        panelSupplier.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("DATA SUPPLIER");

        tabel_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_supplier);

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel12.setText("ID Supplier");

        jLabel13.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel13.setText("Nama Supplier");

        jLabel14.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel14.setText("No. Telepon");

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel15.setText("Alamat");

        BTadd_supplier.setText("Add Data");
        BTadd_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTadd_supplierActionPerformed(evt);
            }
        });

        BTedit_supplier.setText("Edit Data");
        BTedit_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTedit_supplierActionPerformed(evt);
            }
        });

        BTdelete_supplier.setText("Delete Data");
        BTdelete_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTdelete_supplierActionPerformed(evt);
            }
        });

        BTrefresh_supplier.setText("Refresh All");
        BTrefresh_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTrefresh_supplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSupplierLayout = new javax.swing.GroupLayout(panelSupplier);
        panelSupplier.setLayout(panelSupplierLayout);
        panelSupplierLayout.setHorizontalGroup(
            panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplierLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSupplierLayout.createSequentialGroup()
                        .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTidSupplier_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTnama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTnomor_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTalamat_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addGroup(panelSupplierLayout.createSequentialGroup()
                                .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTrefresh_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelSupplierLayout.createSequentialGroup()
                                        .addComponent(BTadd_supplier)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTedit_supplier)))
                                .addGap(18, 18, 18)
                                .addComponent(BTdelete_supplier)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(panelSupplierLayout.createSequentialGroup()
                        .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelSupplierLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BTadd_supplier, BTdelete_supplier, BTedit_supplier});

        panelSupplierLayout.setVerticalGroup(
            panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplierLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSupplierLayout.createSequentialGroup()
                        .addComponent(JTidSupplier_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTnama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTnomor_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTalamat_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTadd_supplier)
                            .addComponent(BTedit_supplier)
                            .addComponent(BTdelete_supplier))
                        .addGap(33, 33, 33)
                        .addComponent(BTrefresh_supplier))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        mainPanel.add(panelSupplier, "card3");

        javax.swing.GroupLayout panelPenjualanLayout = new javax.swing.GroupLayout(panelPenjualan);
        panelPenjualan.setLayout(panelPenjualanLayout);
        panelPenjualanLayout.setHorizontalGroup(
            panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        panelPenjualanLayout.setVerticalGroup(
            panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        mainPanel.add(panelPenjualan, "card4");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // =========================================================================================================

    // EVENT SIDE PANEL
    private void dataBarang_tabButMouseClicked(java.awt.event.MouseEvent evt) {
        panelBarang.setVisible(true);
        panelPenjualan.setVisible(false);
        panelSupplier.setVisible(false);
    }

    private void dataSupplier_tabButMouseClicked(java.awt.event.MouseEvent evt) {
        panelBarang.setVisible(false);
        panelPenjualan.setVisible(false);
        panelSupplier.setVisible(true);
    }

    private void dataPenjualan_tabButMouseClicked(java.awt.event.MouseEvent evt) {
    }

    private void dataBarang_tabButMouseEntered(java.awt.event.MouseEvent evt) {
        dataBarang_tabBut.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        dataBarang_tabBut.setBackground(new Color(255,186,0));
    }

    private void dataSupplier_tabButMouseEntered(java.awt.event.MouseEvent evt) {
        dataSupplier_tabBut.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        dataSupplier_tabBut.setBackground(new Color(255,186,0));
    }

    private void dataPenjualan_tabButMouseEntered(java.awt.event.MouseEvent evt) {
        dataPenjualan_tabBut.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        dataPenjualan_tabBut.setBackground(new Color(255,186,0));
    }

    private void dataBarang_tabButMouseExited(java.awt.event.MouseEvent evt) {
        dataBarang_tabBut.setBackground(new Color(255,153,0));
    }

    private void dataSupplier_tabButMouseExited(java.awt.event.MouseEvent evt) {
        dataSupplier_tabBut.setBackground(new Color(255,153,0));
    }
    private void dataPenjualan_tabButMouseExited(java.awt.event.MouseEvent evt) {
        dataPenjualan_tabBut.setBackground(new Color(255,153,0));
    }

    private void logout_labelMouseEntered(java.awt.event.MouseEvent evt) {
        logout_label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    private void logout_labelMouseClicked(java.awt.event.MouseEvent evt) {
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda ingi keluar", "Log Out", JOptionPane.YES_NO_OPTION);
        if(ok == 0) {
            this.setVisible(false);
            new loginForm().setVisible(true);
        }
    }


    // EVENT PANEL DATA BARANG
    private void BTinsert_barangActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            stat.executeUpdate("Insert Into databarang Values('"
            +JTkode_barang.getText()+"','"
            +JTnama_barang.getText()+"','"
            +JTsatuan_barang.getText()+"','"
            +JTsupplier_barang.getText()+"','"
            +JTstok_barang.getText()+"','"
            +JTharga_barang.getText()+"')"
            );
            kosongkan_formBarang();
            loadTabel_barang();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {
        int i_FadilArdiansyah = tabel_barang.getSelectedRow();
        if (i_FadilArdiansyah == -1) {
            return;
        }

        id_barang = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 0);
        String data1 = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 1);
        String data2 = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 2);
        String data3 = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 3);
        String data4 = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 4);
        String data5 = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 5);
        String data6 = (String)tabel_barang.getValueAt(i_FadilArdiansyah, 6);


        JTkode_barang.setText(id_barang);
        JTnama_barang.setText(data1);
        JTsatuan_barang.setText(data2);
        JTsupplier_barang.setText(data3);
        CBnamaSupplier.setSelectedItem(data4);
        JTstok_barang.setText(data5);
        JTharga_barang.setText(data6);
    }

    private void BTedit_barangActionPerformed(java.awt.event.ActionEvent evt) {
        int ok = JOptionPane.showConfirmDialog(null, "Apakah ingin mengupdate data ini?"
        , "Edit Data", JOptionPane.YES_NO_CANCEL_OPTION);
        try {
            PreparedStatement statEdit = con.prepareStatement(
                "Update databarang set kode_barang=?, nama_barang=?, satuan=?, id_supplier=?, stok=?, harga=? Where kode_barang='"
                +id_barang+"'"
            );
            if (ok == 0) {
                try {
                    statEdit.setString(1, JTkode_barang.getText());
                    statEdit.setString(2, JTnama_barang.getText());
                    statEdit.setString(3, JTsatuan_barang.getText());
                    statEdit.setString(4, JTsupplier_barang.getText());
                    statEdit.setInt(5, Integer.parseInt(JTstok_barang.getText()));
                    statEdit.setInt(6, Integer.parseInt(JTharga_barang.getText()));
                    statEdit.executeUpdate();
                    loadTabel_barang();
                    kosongkan_formBarang();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Update "+e);
                }
            }
        } catch (HeadlessException | SQLException e) {
        }
    }

    private void BTdelete_barangActionPerformed(java.awt.event.ActionEvent evt) {
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Yakin Menghapus Data?",
        "Hapus Data", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            try {
                String sql = "Delete From tbl_bayarkas where KodeBayar='"
                +JTkode_barang.getText()+"'";
                PreparedStatement statDelete = con.prepareStatement(sql);
                statDelete.executeUpdate();
                loadTabel_barang();
                kosongkan_formBarang();

                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal "+e);
            }
        }
    }

    private void JTsupplier_barangMouseClicked(java.awt.event.MouseEvent evt) {
        idSupplier_barang();
    }

    private void BTrefresh_barangActionPerformed(java.awt.event.ActionEvent evt) {
        comboBox_formbarang();
        kosongkan_formBarang();
        loadTabel_barang();
    }

    // EVENT PANEL DATA SUPPLIER
    private void BTadd_supplierActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            stat.executeUpdate("Insert Into datasupplier Values('"
            +JTidSupplier_supplier.getText()+"','"
            +JTnama_supplier.getText()+"','"
            +JTnomor_supplier.getText()+"','"
            +JTalamat_supplier.getText()+"')"
            );
            kosongkan_formSupplier();
            loadTabel_supplier();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }

    private void BTedit_supplierActionPerformed(java.awt.event.ActionEvent evt) {
        int ok = JOptionPane.showConfirmDialog(null, "Apakah ingin mengupdate data ini?"
        , "Edit Data", JOptionPane.YES_NO_CANCEL_OPTION);
        try {
            PreparedStatement statEdit = con.prepareStatement(
                "Update datasupplier set id_supplier=?, nama_supplier=?, no_telepon=?, alamat=? Where id_supplier='"
                +id_supplier+"'"
            );
            if (ok == 0) {
                try {
                    statEdit.setString(1, JTidSupplier_supplier.getText());
                    statEdit.setString(2, JTnama_supplier.getText());
                    statEdit.setString(3, JTnomor_supplier.getText());
                    statEdit.setString(4, JTalamat_supplier.getText());
                    statEdit.executeUpdate();
                    loadTabel_supplier();
                    kosongkan_formSupplier();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
                } catch (HeadlessException | NumberFormatException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Update "+e);
                }
            }
        } catch (HeadlessException | SQLException e) {
        }
    }

    private void BTdelete_supplierActionPerformed(java.awt.event.ActionEvent evt) {
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Yakin Menghapus Data?",
        "Hapus Data", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            try {
                String sql = "Delete From datasupplier where id_supplier='"
                +JTidSupplier_supplier.getText()+"'";
                PreparedStatement statDelete = con.prepareStatement(sql);
                statDelete.executeUpdate();
                loadTabel_supplier();
                kosongkan_formSupplier();

                JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Hapus Data Gagal "+e);
            }
        }
    }

    private void BTrefresh_supplierActionPerformed(java.awt.event.ActionEvent evt) {
        kosongkan_formSupplier();
        loadTabel_supplier();
    }

    private void tabel_supplierMouseClicked(java.awt.event.MouseEvent evt) {
        int i_FadilArdiansyah = tabel_supplier.getSelectedRow();
        if (i_FadilArdiansyah == -1) {
            return;
        }

        id_supplier = (String)tabel_supplier.getValueAt(i_FadilArdiansyah, 0);
        String data1 = (String)tabel_supplier.getValueAt(i_FadilArdiansyah, 1);
        String data2 = (String)tabel_supplier.getValueAt(i_FadilArdiansyah, 2);
        String data3 = (String)tabel_supplier.getValueAt(i_FadilArdiansyah, 3);


        JTidSupplier_supplier.setText(id_supplier);
        JTnama_supplier.setText(data1);
        JTnomor_supplier.setText(data2);
        JTalamat_supplier.setText(data3);
    }

    // =========================================================================================================

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTadd_supplier;
    private javax.swing.JButton BTdelete_barang;
    private javax.swing.JButton BTdelete_supplier;
    private javax.swing.JButton BTedit_barang;
    private javax.swing.JButton BTedit_supplier;
    private javax.swing.JButton BTinsert_barang;
    private javax.swing.JButton BTrefresh_barang;
    private javax.swing.JButton BTrefresh_supplier;
    private javax.swing.JComboBox<String> CBnamaSupplier;
    private javax.swing.JTextField JTalamat_supplier;
    private javax.swing.JTextField JTharga_barang;
    private javax.swing.JTextField JTidSupplier_supplier;
    private javax.swing.JTextField JTkode_barang;
    private javax.swing.JTextField JTnama_barang;
    private javax.swing.JTextField JTnama_supplier;
    private javax.swing.JTextField JTnomor_supplier;
    private javax.swing.JTextField JTsatuan_barang;
    private javax.swing.JTextField JTstok_barang;
    private javax.swing.JTextField JTsupplier_barang;
    private javax.swing.JPanel background;
    private javax.swing.JPanel dataBarang_tabBut;
    private javax.swing.JLabel dataBarang_tg;
    private javax.swing.JPanel dataPenjualan_tabBut;
    private javax.swing.JPanel dataSupplier_tabBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logout_label;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBarang;
    private javax.swing.JPanel panelPenjualan;
    private javax.swing.JPanel panelSupplier;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_supplier;
    // End of variables declaration//GEN-END:variables

    private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/tokoSembako", "root", "");
            stat = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Method Panel data barang
    public final void loadTabel_barang() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("kode barang");
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Satuan");
        tabel.addColumn("Kode Supplier");
        tabel.addColumn("Supplier");
        tabel.addColumn("Stok Barang");
        tabel.addColumn("Harga Barang");
        tabel_barang.setModel(tabel);

        try {
            res = stat.executeQuery("Select * From databarang inner join datasupplier on databarang.id_supplier=datasupplier.id_supplier");
            while (res.next()) {
            tabel.addRow(new Object[]{
                res.getString("kode_barang"),
                res.getString("nama_barang"),
                res.getString("satuan"),
                res.getString("id_supplier"),
                res.getString("nama_supplier"),
                res.getString("stok"),
                res.getString("harga")
            });
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosongkan_formBarang() {
        JTkode_barang.setText("");
        JTnama_barang.setText("");
        JTsatuan_barang.setText("");
        CBnamaSupplier.setSelectedIndex(-1);
        JTsupplier_barang.setText("");
        JTstok_barang.setText("");
        JTharga_barang.setText("");
    }

    private void comboBox_formbarang() {
        try {
            String sql = "select nama_supplier from datasupplier order by nama_supplier asc";
            res = stat.executeQuery(sql);
            CBnamaSupplier.removeAllItems();
            while (res.next()) {
                CBnamaSupplier.addItem(res.getString("nama_supplier"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void idSupplier_barang() {
        try {
            String sql = "select id_supplier from datasupplier where nama_supplier='"+CBnamaSupplier.getSelectedItem()+"'";
            res = stat.executeQuery(sql);

            while (res.next()) {
                {   
                    JTsupplier_barang.setText(res.getString("id_supplier"));
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // Method Panel data supplier
    public final void loadTabel_supplier() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Supplier");
        tabel.addColumn("Nama Supplier");
        tabel.addColumn("No. Telepon");
        tabel.addColumn("Alamat");
        tabel_supplier.setModel(tabel);

        try {
            res = stat.executeQuery("Select * From datasupplier");
            while (res.next()) {
            tabel.addRow(new Object[]{
                res.getString("id_supplier"),
                res.getString("nama_supplier"),
                res.getString("no_telepon"),
                res.getString("alamat")
            });
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosongkan_formSupplier() {
        JTidSupplier_supplier.setText("");
        JTnama_supplier.setText("");
        JTnomor_supplier.setText("");
        JTalamat_supplier.setText("");
    }
}
